swagger: "2.0"
info:
  description: "Documentação do projeto Vough API!"
  version: "1.0.0"
  title: "Vough"

basePath: "/api/"
schemes:
- "http"

tags:
- name: "orgs"
  description: "Endpoints referente as ações das organizações."

paths:
  /orgs/:
    post:
      summary: "Endpoint de listagem de organizações."
      tags:
      - orgs
      operationId: "create"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Objeto Proprietário que será adicionado à plataforma."
        required: true
        schema:
          $ref: "#/definitions/CreateOrganization"
      responses:
        201:
          description: "Created"
    get:
      summary: "Endpoint de listagem de organizações."
      tags:
      - orgs
      operationId: "list"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        200:
          type: array
          description: "OK"
          schema:
            items:
              $ref: "#/definitions/Organization"
        

  /orgs/{username}/:
    get:
      summary: "Endpoint de detalhes de uma organização."
      tags:
      - orgs
      operationId: "detail"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      - name: "username"
        in: "path"
        description: "Username da Organização"
        required: true
        type: string
      responses:
        200:
          type: object
          description: "OK"
          schema:
            $ref: "#/definitions/Organization"
        404:
            description: "Not found"
            schema:
              type: object
              properties:
                detail:
                  type: object
                  example: "Não encontrado."
    delete:
      summary: "Endpoint de remoção de uma organização."
      tags:
      - orgs
      operationId: "delete"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      - name: "username"
        in: "path"
        description: "Username da Organização"
        required: true
        type: string
      responses:
        204:
          type: object
          description: "No Content"
        404:
            description: "Not Found"
            schema:
              type: object
              properties:
                detail:
                  type: object
                  example: "Não encontrado."
              
definitions:
  Organization:
    type: object
    properties:
      username:
        type: string
        maximum: 255
        example: "instruct-br"
      name:
        type: string
        maximum: 255
        example: "Instruct"          
      score:
        type: integer
        example: 4
  CreateOrganization:
    type: object
    properties:
      username:
        type: string
        maximum: 255
        example: "instruct-br"
      name:
        type: string
        maximum: 255
        example: "Instruct"          

