# Generated by Django 3.1.1 on 2021-03-28 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={'verbose_name': 'organização', 'verbose_name_plural': 'organizações'},
        ),
        migrations.AlterField(
            model_name='organization',
            name='login',
            field=models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='Login'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nome da Organização'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='score',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Score'),
        ),
    ]
